#
# Configuration for ACI Fabric
#
aci_config:
  system_id: KubeSpray             # Every opflex cluster must have a distict ID
  apic_hosts:                   # List of APIC hosts to connect for APIC API
  - 10.192.73.30
  - 10.192.73.31
  - 10.192.73.32
  vmm_domain:                   # Kubernetes container domain configuration
    encap_type: vxlan           # Encap mode: vxlan or vlan
    mcast_range:                # Every opflex VMM must use a distinct range
      start: 225.22.1.1
      end: 225.22.255.255
    nested_inside:              # Include if nested inside a VMM;
                                #   required for CloudFoundry
                                #   supported for Kubernetes
     type: vmware              # Specify the VMM vendor (supported: vmware)
     name: my6.7-vCenter            # Specify the name of the VMM domain

  # The following resources must already exist on the APIC.
  # They are used, but not created, by the provisioning tool.
  aep: vCenter6.7_AEP             # The AEP for ports/VPCs used by this cluster
  vrf:                          # This VRF used to create all kubernetes EPs
    name: mykube-vrf
    tenant: KubeSpray             # This can be system-id or common
  l3out:
    name: mykube_l3out          # Used to provision external IPs
    external_networks:
    - mykube_extepg             # Used for external contracts

#
# Networks used by ACI containers
#
net_config:
  node_subnet: 10.32.0.1/16
  pod_subnet: 10.33.0.1/16
  extern_dynamic: 10.34.0.1/24
  extern_static: 10.35.0.1/24 # Subnet to use for static external IPs 
  node_svc_subnet: 10.36.0.1/24 # Subnet to use for service graph
  kubeapi_vlan: 4011 
  service_vlan: 4013 
  infra_vlan: 4093
# The VLAN used by for nodes to node API communications # The VLAN used by LoadBalancer services
# The ACI infra VLAN used to establish the OpFlex tunnel with the leaf
  #interface_mtu: 1600          # min = 1280 for ipv6, max = 8900 for VXLAN


#
# Configuration for container registry
# Update if a custom container registry has been setup
#
registry:
  image_prefix: noiro                   # e.g: registry.example.com/noiro
  # image_pull_secret: secret_name      # (if needed)
